In [51]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import torch

In [4]:
%pip install torch

  Using cached torch-2.6.0-cp312-cp312-win_amd64.whl.metadata (28 kB)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Using cached torch-2.6.0-cp312-cp312-win_amd64.whl (204.1 MB)
Using cached sympy-1.13.1-py3-none-any.whl (6.2 MB)
Using cached networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   --------------------------------- ------ 1.0/1.2 MB 6.3 MB/s eta 0:00:01
   --------------------------------- ------ 1.0/1.2 MB 6.3 MB/s eta 0:00:01
   --------------------------------- ------ 1.0/1.2 MB 6.3 MB/s eta 0:00:01
   --------------------------------- ------ 1.0/1.2 MB 6.3 MB/s eta 0:00:01
   --------------------------------- ------ 1.0/1.2 MB 6.3 MB/s eta 0:00:01
   --------------------------------- ------ 1.0/1.2 MB 6.3 MB/s eta 0:00:01
   --------------------------------- ------ 1.0/1.2 MB 6.3 MB/s eta 0:00:01
   -------------------------------


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# SGD
def SGD (learning_rate: int = 0.01, initial_params: np.ndarray = None,x_coors=):
    """Implements Stochastic Gradient Descent"""

    if initial_params is None:
        raise ValueError('Initial parameter not set')
    else:
        for stopping condition not met
        # Draw a random minibatch from X Y Z

        # Compute Gradient

        # Apply Update


SyntaxError: expected default value expression (2569341910.py, line 2)

NameError: name 'X' is not defined

In [52]:
X = np.load('X.npy')
Y = np.load('Y.npy')
Z = np.load('Z.npy')

In [53]:
Z.shape

(100, 100)

In [54]:
X.shape

(100, 100)

In [55]:
Z

array([[-5.9450253 , -6.14032323, -6.11528801, ..., -4.55845119,
        -4.26035725, -4.06646221],
       [-5.94363112, -6.44719699, -6.49714305, ..., -4.66276267,
        -4.77629103, -4.79772684],
       [-5.93335956, -6.50994802, -6.54581242, ..., -4.87744632,
        -5.24065283, -5.38983275],
       ...,
       [-3.8613936 , -3.57884955, -3.73656303, ..., -3.56755886,
        -3.27800747, -3.16005986],
       [-3.70196721, -3.70775382, -3.95689165, ..., -3.54609977,
        -3.69450821, -3.81178257],
       [-3.60414205, -3.96948753, -4.3325957 , ..., -3.50948258,
        -4.09724403, -4.44919605]], shape=(100, 100))

In [56]:
random_x = np.random.choice(first_row_x)
random_y = np.random.choice(first_col_y)
random_z = np.random.choice(Z)


NameError: name 'first_row_x' is not defined

In [57]:
X.ndim

2

In [58]:
Y

array([[-48.        , -48.        , -48.        , ..., -48.        ,
        -48.        , -48.        ],
       [-47.70707071, -47.70707071, -47.70707071, ..., -47.70707071,
        -47.70707071, -47.70707071],
       [-47.41414141, -47.41414141, -47.41414141, ..., -47.41414141,
        -47.41414141, -47.41414141],
       ...,
       [-19.58585859, -19.58585859, -19.58585859, ..., -19.58585859,
        -19.58585859, -19.58585859],
       [-19.29292929, -19.29292929, -19.29292929, ..., -19.29292929,
        -19.29292929, -19.29292929],
       [-19.        , -19.        , -19.        , ..., -19.        ,
        -19.        , -19.        ]], shape=(100, 100))

In [59]:
X[0]

array([-20.        , -19.5959596 , -19.19191919, -18.78787879,
       -18.38383838, -17.97979798, -17.57575758, -17.17171717,
       -16.76767677, -16.36363636, -15.95959596, -15.55555556,
       -15.15151515, -14.74747475, -14.34343434, -13.93939394,
       -13.53535354, -13.13131313, -12.72727273, -12.32323232,
       -11.91919192, -11.51515152, -11.11111111, -10.70707071,
       -10.3030303 ,  -9.8989899 ,  -9.49494949,  -9.09090909,
        -8.68686869,  -8.28282828,  -7.87878788,  -7.47474747,
        -7.07070707,  -6.66666667,  -6.26262626,  -5.85858586,
        -5.45454545,  -5.05050505,  -4.64646465,  -4.24242424,
        -3.83838384,  -3.43434343,  -3.03030303,  -2.62626263,
        -2.22222222,  -1.81818182,  -1.41414141,  -1.01010101,
        -0.60606061,  -0.2020202 ,   0.2020202 ,   0.60606061,
         1.01010101,   1.41414141,   1.81818182,   2.22222222,
         2.62626263,   3.03030303,   3.43434343,   3.83838384,
         4.24242424,   4.64646465,   5.05050505,   5.45

In [60]:
Y[:,0]

array([-48.        , -47.70707071, -47.41414141, -47.12121212,
       -46.82828283, -46.53535354, -46.24242424, -45.94949495,
       -45.65656566, -45.36363636, -45.07070707, -44.77777778,
       -44.48484848, -44.19191919, -43.8989899 , -43.60606061,
       -43.31313131, -43.02020202, -42.72727273, -42.43434343,
       -42.14141414, -41.84848485, -41.55555556, -41.26262626,
       -40.96969697, -40.67676768, -40.38383838, -40.09090909,
       -39.7979798 , -39.50505051, -39.21212121, -38.91919192,
       -38.62626263, -38.33333333, -38.04040404, -37.74747475,
       -37.45454545, -37.16161616, -36.86868687, -36.57575758,
       -36.28282828, -35.98989899, -35.6969697 , -35.4040404 ,
       -35.11111111, -34.81818182, -34.52525253, -34.23232323,
       -33.93939394, -33.64646465, -33.35353535, -33.06060606,
       -32.76767677, -32.47474747, -32.18181818, -31.88888889,
       -31.5959596 , -31.3030303 , -31.01010101, -30.71717172,
       -30.42424242, -30.13131313, -29.83838384, -29.54

In [61]:
first_row_x,first_col_y = X[0] , Y[:,0]

In [73]:
X = np.load('X.npy')
Y = np.load('Y.npy')
Z = np.load('Z.npy')


In [63]:
X

array([[-20.        , -19.5959596 , -19.19191919, ...,  19.19191919,
         19.5959596 ,  20.        ],
       [-20.        , -19.5959596 , -19.19191919, ...,  19.19191919,
         19.5959596 ,  20.        ],
       [-20.        , -19.5959596 , -19.19191919, ...,  19.19191919,
         19.5959596 ,  20.        ],
       ...,
       [-20.        , -19.5959596 , -19.19191919, ...,  19.19191919,
         19.5959596 ,  20.        ],
       [-20.        , -19.5959596 , -19.19191919, ...,  19.19191919,
         19.5959596 ,  20.        ],
       [-20.        , -19.5959596 , -19.19191919, ...,  19.19191919,
         19.5959596 ,  20.        ]], shape=(100, 100))

In [64]:
# Figure plotting

fig =  go.Figure(
    data = [go.Surface(z=Z, x=X, y=Y, showscale=False)]
)

fig.update_layout(title = dict(text = "Dummy"),
                  width = 1000,height = 500)

fig.show()


In [65]:
# Get the shape of the meshgrid
rows, cols = X.shape

# Generate a random row and column index
random_row = np.random.randint(0, rows)
random_col = np.random.randint(0, cols)

# Extract the random coordinate
random_x = X[random_row, random_col]
random_y = Y[random_row, random_col]

print(f"Randomly chosen coordinate: ({random_x}, {random_y})")

Randomly chosen coordinate: (19.19191919191919, -31.595959595959595)


In [66]:
X = np.load('X.npy')
Y = np.load('Y.npy')
Z = np.load('Z.npy')


# Get the shape of the meshgrid
rows, cols = X.shape

# Generate a random row and column index
random_row = np.random.randint(0, rows)
random_col = np.random.randint(0, cols)

# Extract the random coordinate
random_x = X[random_row, random_col]
random_y = Y[random_row, random_col]
random_z = Z[random_row,random_col]

print(f"Randomly chosen coordinate: ({random_x}, {random_y})")
fig.add_trace(
    go.Scatter3d(
        x=[random_x],
        y=[random_y],
        z=[random_z],
        mode='markers',
        marker=dict(size=2, color='black'),
        name='Random Point'
    )
)
fig.update_layout(template = 'plotly_dark')
fig.show()

Randomly chosen coordinate: (15.151515151515149, -22.80808080808081)


In [67]:
# Get the shape of the grid
rows, cols = X.shape

# Choose a random index
i = np.random.randint(0, rows)
j = np.random.randint(0, cols)

# Get corresponding x, y, and z
random_x = X[i, j]
random_y = Y[i, j]
random_z = Z[i, j]


In [68]:
random_x,random_y,random_z

(np.float64(-1.8181818181818201),
 np.float64(-43.02020202020202),
 np.float64(3.2022852326939617))

In [69]:

fig =  go.Figure(
    data = [go.Surface(z=Z, x=X, y=Y, showscale=False)]
)

fig.add_trace(
    go.Scatter3d(
        x=[random_x],
        y=[random_y],
        z=[random_z],
        mode='markers',
        marker=dict(size=2, color='black'),
        name='Random Point'
    )
)
fig.update_layout(template = 'plotly_dark')

fig.update_layout(
    scene_camera=dict(
        eye=dict(x=1.25, y=1.25, z=1.25), # Initial camera position
    ),
    margin=dict(l=0, r=0, b=0, t=0)
)

fig.show()



In [70]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def SGD(X: np.ndarray,
        Y: np.ndarray,
        Z: np.ndarray,
        lr: float = 0.1,
        steps: int = 50,
        seed: int = 42):
    """
    Simple Stochastic Gradient Descent on a surface.

    Parameters:
    - X, Y, Z: Meshgrid arrays of shape (N, N)
    - lr: Learning rate
    - steps: Number of optimization steps
    """

    np.random.seed(seed)
    trace_x, trace_y, trace_z = [], [], []

    # Pick a random starting index
    rows, cols = X.shape
    i = np.random.randint(0, rows)
    j = np.random.randint(0, cols)

    x, y = X[i, j], Y[i, j]

    for step in range(steps):
        # Compute gradient (numerical approximation)
        delta = 1e-3
        i_x = np.abs(X[0] - x).argmin()
        i_y = np.abs(Y[:,0] - y).argmin()
        
        z = Z[i_y, i_x]

        # Approximate gradient using finite differences
        z_dx = Z[i_y, np.clip(i_x + 1, 0, cols - 1)]
        z_dy = Z[np.clip(i_y + 1, 0, rows - 1), i_x]

        dz_dx = (z_dx - z) / delta
        dz_dy = (z_dy - z) / delta

        # Gradient descent update
        x = x - lr * dz_dx
        y = y - lr * dz_dy

        # Clamp to grid
        x = np.clip(x, X.min(), X.max())
        y = np.clip(y, Y.min(), Y.max())
        i_x = np.abs(X[0] - x).argmin()
        i_y = np.abs(Y[:,0] - y).argmin()
        z = Z[i_y, i_x]

        trace_x.append(x)
        trace_y.append(y)
        trace_z.append(z)

    return trace_x, trace_y, trace_z


In [75]:
import numpy as np
import plotly.graph_objs as go


# SGD Trace (from earlier function)
tx, ty, tz = SGD(X, Y, Z, lr=0.2, steps=50)

# Surface
surface = go.Surface(z=Z, x=X, y=Y, colorscale='Viridis', opacity=0.7)

# Frames for animation
frames = []
for i in range(len(tx)):
    frame = go.Frame(
        data=[
            go.Scatter3d(
                x=tx[:i+1],
                y=ty[:i+1],
                z=tz[:i+1],
                mode='lines+markers',
                line=dict(color='red', width=5),
                marker=dict(size=5, color='black')
            )
        ],
        name=f'frame{i}'
    )
    frames.append(frame)

# Layout with rotating eye/camera
layout = go.Layout(
    title="SGD Path on 3D Surface",
    scene=dict(
        xaxis=dict(title='X'),
        yaxis=dict(title='Y'),
        zaxis=dict(title='Z'),
        camera=dict(
            eye=dict(x=1.25, y=1.25, z=1.25)  # starting eye position
        )
    ),
    updatemenus=[
        dict(
            type="buttons",
            buttons=[
                dict(label="Play",
                     method="animate",
                     args=[None, {
                         "frame": {"duration": 100, "redraw": True},
                         "fromcurrent": True,
                         "transition": {"duration": 0}
                     }]),
                dict(label="Pause",
                     method="animate",
                     args=[[None], {
                         "frame": {"duration": 0, "redraw": False},
                         "mode": "immediate",
                         "transition": {"duration": 0}
                     }])
            ]
        )
    ]
)

# Create figure
fig = go.Figure(
    data=[surface,
          go.Scatter3d(
              x=[tx[0]],
              y=[ty[0]],
              z=[tz[0]],
              mode='markers',
              marker=dict(size=5, color='red'))],
    layout=layout,
    frames=frames
)

fig.show()
